import './globals.css'

export const metadata = {
  title: 'Set My Space',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-gray-100 via-gray-200 to-gray-300'>{children}</body>
    </html>
  )
}
